
FROM node:20-bullseye

WORKDIR /app


COPY package*.json ./
RUN npm install -g npm@latest
RUN npm install
RUN npm rebuild rollup -f


COPY . .


EXPOSE 5173


CMD ["npm", "run", "dev", "--", "--host"]
